##image: cirrusci/flutter:latest
#
##before_script:
##  - flutter channel beta
##  - flutter upgrade
##  - flutter config --enable-web
##  - flutter pub get
#
#build_and_test_web_app:
#  stage: build
#  image: cirrusci/flutter:stable
#  before_script:
#    - flutter config --enable-web
#    - flutter pub get
#  script:
#    - flutter build web
#    - flutter analyze
#    - flutter test
#  artifacts:
#    paths:
#      - build/web
#
#pages:
#  stage: deploy
#  script:
#    - cp -r build/web public
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
#
#
#
##pages:
##  stage: deploy
##  script:
##    - flutter build web --base-href "/vibechecker/"
##    - cp -r build/web public
##  artifacts:
##    paths:
##      - public
##  only:
##    - live\


stages:
  - check:static
  - check:tests
  - test
  - build:prepare
  - release

before_script:
  #  - npm i -g firebase-tools
  - git status
  - git fetch --all
#  - git checkout stable
  - flutter doctor
  - flutter doctor -v
  - flutter channel
#  - flutter upgrade
  - flutter config --enable-web
  - flutter pub get
#  - flutter channel beta


dart-formatter:
  stage: check:static
  interruptible: true
  script: flutter format --dry-run --set-exit-if-changed .

dart-analyzer:
  stage: check:static
  interruptible: true
  script: flutter analyze --fatal-infos --fatal-warnings

code-generation-mismatch-check:
  image: cirrusci/flutter:latest
  stage: check:static
  interruptible: true
  script:
    - fvm flutter pub get
    - fvm flutter pub run build_runner build --delete-conflicting-outputs --fail-on-severe
    - (( $(git status --untracked-files=no --porcelain|wc -l) == 0 )) || { echo >&2 "Some changes in generated files detected"; exit 1; }

generate-skia-shaders-cache:
  image: volkovpishet/flutter-android:1
  stage: build:prepare
  when: manual
  cache:
    policy: push
    paths:
      - flutter_shaders_warm_up_data.sksl.json
  script:
    - run-emulator
    - fvm flutter drive --profile --cache-sksl --purge-persistent-cache --write-sksl-on-exit flutter_shaders_warm_up_data.sksl.json --driver=test_driver/integration_test.dart --target=test/shaders_warm_up_test.dart

tests:
  stage: check:tests
  script:
    - flutter test
