stages:
  - build
  - test
#  - deploy

build-job:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - flutter config --enable-web
    - flutter pub get
  script:
    - flutter build web
    - flutter analyze
    - flutter test
  artifacts:
    paths:
      - build/web/icons
  only:
    - frontend-ci

lint-test-job:
  stage: test
  image: cirrusci/flutter:stable
  interruptible: true
  before_script:
    - flutter pub get
  script:
    - echo "Checking code formatting and analysis of it."
    - dart format lib
    - flutter analyze --fatal-infos --fatal-warnings
    - flutter analyze
    - echo "The code is overall good formatted. No lint issues found."
  only:
    - frontend-ci

unit-test-job:
  stage: test
  image: cirrusci/flutter:stable
  interruptible: true
  before_script:
    - flutter pub get
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - flutter test
    - echo "Code coverage is 100%"
  only:
    - frontend-ci

#deploy-job:
#  stage: deploy
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
