##image: cirrusci/flutter:latest
#
##before_script:
##  - flutter channel beta
##  - flutter upgrade
##  - flutter config --enable-web
##  - flutter pub get
#
#build_and_test_web_app:
#  stage: build
#  image: cirrusci/flutter:stable
#  before_script:
#    - flutter config --enable-web
#    - flutter pub get
#  script:
#    - flutter build web
#    - flutter analyze
#    - flutter test
#  artifacts:
#    paths:
#      - build/web
#
#pages:
#  stage: deploy
#  script:
#    - cp -r build/web public
#  artifacts:
#    paths:
#      - public
#  only:
#    - master
#
#
#
##pages:
##  stage: deploy
##  script:
##    - flutter build web --base-href "/vibechecker/"
##    - cp -r build/web public
##  artifacts:
##    paths:
##      - public
##  only:
##    - live\

stages:        # List of stages for jobs, and their order of execution
  - test
  - deploy

#before_script:
#  #  - npm i -g firebase-tools
#  - git status
#  - git fetch --all
##  - git checkout stable
#  - flutter doctor
#  - flutter doctor -v
#  - flutter channel beta
##  - flutter upgrade
#  - flutter config --enable-web
#  - flutter pub get
##  - flutter channel beta

#before_script:
#  - flutter pub get

cache:
  paths:
    - ~/.pub-cache/

dart-formatter-and-analyzer: # Analog of lint test job
  stage: test
  image: cirrusci/flutter:stable
  interruptible: true
  script:
    - echo "Checking code formatting and analysis."
    - dart format --dry-run --set-exit-if-changed
    - flutter analyze --fatal-infos --fatal-warnings
    - echo "The code is overall good formatted."

unit-test:
  stage: test
  image: cirrusci/flutter:stable
  interruptible: true
  script:
    - echo "Running unit tests... This will take about 60 seconds."
#    - flutter packages get
    - flutter test
    - echo "Code coverage is 90%"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # Runs if *both* previous jobs complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

